version: "3.1"
services:
  web:
    image: odoo:16
    container_name: web-odoo-morons
    depends_on:
      - db
    volumes:
      - odoo-web-data-morons:/var/lib/odoo
      - ./config:/etc/odoo
      - ./local-addons:/mnt/extra-addons
    environment:
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo
  db:
    image: postgres:13
    container_name: db-odoo-morons
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-morons:/var/lib/postgresql/data/pgdata
    networks:
      - odoo
  pgadmin:
    container_name: pgadmin-odoo-morons
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: amdin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5433:80
    networks:
      - odoo
    restart: unless-stopped
  proxy:
    depends_on:
            - web
    container_name: odoo_proxy-morons
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
        - "8069:8069"
    networks:
      - odoo

networks:
  odoo:
    driver: bridge


volumes:
  odoo-web-data-morons:
  odoo-db-data-morons:
  pgadmin:
